apiVersion: apps/v1
kind: Deployment
metadata:
  name: ffmpeg-conv
  labels:
    app: ffmpeg
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ffmpeg
  template:
    metadata:
      labels:
        app: ffmpeg
    spec:
      containers:
        - name: ffmpeg
          image: jrottenberg/ffmpeg:3-alpine
          ports:
            - containerPort: 6200
