apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy-lb
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
        - name: haproxy
          image: library/haproxy:2.0
          ports:
            - containerPort: 80